version: '3.7'
services:
  jenkins:
    image: farizree/jenkinsandplugins:latest
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 8.8.8.8
      - 8.8.4.4
